"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
exports.injectAssociations = exports.generateApolloServer = exports.generateSchema = exports.generateCount = exports.generateMutationDelete = exports.generateMutationUpdate = exports.generateMutationCreate = exports.generateAssociationsFields = exports.generateGraphQLType = exports.generateModelTypes = void 0;
var mutationCreateResolver_1 = __importDefault(require("./mutationCreateResolver"));
exports.generateMutationCreate = mutationCreateResolver_1["default"];
var mutationUpdateResolver_1 = __importDefault(require("./mutationUpdateResolver"));
exports.generateMutationUpdate = mutationUpdateResolver_1["default"];
var mutationDeleteResolver_1 = __importDefault(require("./mutationDeleteResolver"));
exports.generateMutationDelete = mutationDeleteResolver_1["default"];
var countResolver_1 = __importDefault(require("./countResolver"));
exports.generateCount = countResolver_1["default"];
var modelTypes_1 = __importDefault(require("./modelTypes"));
exports.generateModelTypes = modelTypes_1["default"];
var graphQLType_1 = __importDefault(require("./graphQLType"));
exports.generateGraphQLType = graphQLType_1["default"];
var schema_1 = __importDefault(require("./schema"));
exports.generateSchema = schema_1["default"];
var generateApolloServer_1 = __importDefault(require("./generateApolloServer"));
exports.generateApolloServer = generateApolloServer_1["default"];
var associationsFields_1 = require("./associationsFields");
exports.injectAssociations = associationsFields_1.injectAssociations;
exports.generateAssociationsFields = associationsFields_1.generateAssociationsFields;
